- hosts: localhost
  tasks:
    - name: build project
      command:
        cmd: mvn clean install

    - name: Login into Dockerhub
      command:
        cmd: docker login -u="aasheeshh" -p="Aarvi19*@"

    - name:  Build an image and push it to a private repo
      command:
        cmd: docker build -t aasheeshh/abctechnology:latest .

    - name:
      command:
        cmd: kubectl apply -f ./k8smenifest/
