- hosts: localhost
  tasks:
    - name: Login into Dockerhub
      docker_login:
        username: aasheeshh
        password: Aarvi19*@

    - name:  Build an image and push it to a private repo
      docker_image:
        build:
          path: .
        name: aasheeshh/abctechnology
        tag: latest
        push: yes
        source: build

    - name: Create a Deployment by reading the definition 
      kubernetes.core.k8s:
        state: present
        src: ./k8smenifest/deployment.yml

    - name:
      kubernetes.core.k8s:
        state: present
        src: ./k8smenifest/service.yml
