---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: abctechnology
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: abctechnology
  replicas: 3 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: abctechnology
    spec:
      containers:
      - name: abctechnology
        image: aasheeshh/abctechnology:latest
        ports:
        - containerPort: 8080
---
